spring:
  # app 이름
  application:
    name: camp
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: ${DB_USERNAME} # 환경 변수 사용, 없을 경우 기본값
    password: ${DB_PASSWORD}
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#gocamping
gocamping:
  api:
    service-key: ${GOCAMPING_API_KEY}

# 웹서버 포트
server:
  port: 9080

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    root: info
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

