CREATE TABLE CAMP_SCRAP (
    SCRAP_ID      NUMBER PRIMARY KEY,
    MEMBER_ID     NUMBER NOT NULL,
    CONTENT_ID    VARCHAR2(20) NOT NULL, -- 캠핑장 고유 ID
    FACLT_NM      VARCHAR2(100),         -- 캠핑장 이름
    FIRST_IMAGE_URL VARCHAR2(255),       -- 대표 이미지 URL
    ADDR1         VARCHAR2(200),         -- 주소
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MEMBER_SCRAP FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT UK_MEMBER_CONTENT UNIQUE (MEMBER_ID, CONTENT_ID) -- 한 회원이 같은 캠핑장을 중복 찜하지 못하도록 설정
);

-- SCRAP_ID 자동 증가를 위한 시퀀스
CREATE SEQUENCE camp_scrap_id_seq
START WITH 1
INCREMENT BY 1;