CREATE TABLE CAMPING_INFO (
    contentId          NUMBER(10) PRIMARY KEY,
    resultCode         VARCHAR2(10),
    resultMsg          VARCHAR2(100),
    numOfRows          NUMBER(5),
    pageNo             NUMBER(5),
    totalCount         NUMBER(10),
    facltNm            VARCHAR2(100),
    lineIntro          VARCHAR2(100),
    intro              CLOB, 
    insrncAt           CHAR(1) CHECK (insrncAt IN ('Y', 'N')), 
    manageSttus        VARCHAR2(20), 
    hvofBgnde          DATE, 
    hvofEnddle         DATE, 
    featureNm          VARCHAR2(2000), 
    induty             VARCHAR2(100), 
    lctCl              VARCHAR2(100),
    doNm               VARCHAR2(50), 
    sigunguNm          VARCHAR2(50), 
    zipcode            VARCHAR2(10), 
    addr1              VARCHAR2(255), 
    addr2              VARCHAR2(255), 
    direction          VARCHAR2(2000), 
    tel                VARCHAR2(20), 
    homepage           VARCHAR2(2000), 
    gnrlSiteCo         NUMBER(5) DEFAULT 0, 
    autoSiteCo         NUMBER(5) DEFAULT 0, 
    glampSiteCo        NUMBER(5) DEFAULT 0, 
    caravSiteCo        NUMBER(5) DEFAULT 0, 
    indvdlCaravSiteCo  NUMBER(5) DEFAULT 0, 
    sitedStnc          NUMBER(10,2),
    glampInnerFclty    VARCHAR2(1000),
    caravInnerFclty    VARCHAR2(1000), 
    operPdCl           VARCHAR2(100),
    operDeCl           VARCHAR2(100), 
    trlerAcmpnyAt      CHAR(1) CHECK (trlerAcmpnyAt IN ('Y', 'N')), 
    caravAcmpnyAt      CHAR(1) CHECK (caravAcmpnyAt IN ('Y', 'N')), 
    sbrsCl             VARCHAR2(1000), 
    themaEnvrnCl       VARCHAR2(255),
    eqpmnLendCl        VARCHAR2(255),
    animalCmgCl        VARCHAR2(255), 
    firstImageUrl      VARCHAR2(2000), 
    createdtime        TIMESTAMP DEFAULT SYSTIMESTAMP,
    modifiedtime       TIMESTAMP DEFAULT SYSTIMESTAMP
);
