CREATE TABLE COMMUNITY (
    CO_ID        NUMBER(10) PRIMARY KEY, 
    MEMBER_ID    NUMBER(10) NOT NULL 
                          REFERENCES MEMBER(member_id)
                          ON DELETE CASCADE,
    TITLE        VARCHAR2(50) NOT NULL,   
    WRITER       VARCHAR2(20) NOT NULL,   
    CONTENT      CLOB NOT NULL,           
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, 
    UPDATED_AT   TIMESTAMP, 
    VIEW_C       NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE member_co_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_set_community_updated_at
BEFORE UPDATE ON COMMUNITY
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
