CREATE TABLE REVIEW (
    REV_ID       NUMBER(10) PRIMARY KEY, 
    CONTENT_ID   NUMBER(10) NOT NULL 
                 REFERENCES CAMPSITES(CONTENT_ID) 
                 ON DELETE CASCADE,
    MEMBER_ID    NUMBER(10) NOT NULL 
                 REFERENCES MEMBER(MEMBER_ID) 
                 ON DELETE CASCADE,
    WRITER       VARCHAR2(20) NOT NULL,  
    CONTENT      CLOB NOT NULL,    
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP, 
    SCORE        NUMBER(10) DEFAULT 0 NOT NULL
                 CHECK (SCORE BETWEEN 1 AND 5)
);

CREATE SEQUENCE review_rev_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_set_review_updated_at
BEFORE UPDATE ON REVIEW
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
