CREATE TABLE SCRAP (
    SCRAP_ID    NUMBER(10) PRIMARY KEY,
    MEMBER_ID   NUMBER(10) NOT NULL
                REFERENCES MEMBER(MEMBER_ID)
                ON DELETE CASCADE,
    CONTENT_ID  NUMBER(10) NOT NULL
                REFERENCES CAMPSITES(CONTENT_ID)
                ON DELETE CASCADE,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE camp_scrap_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
